#!/usr/bin/env bash
# .platform/hooks/postdeploy/02_configure_nginx_ssl.sh
# Configure nginx to use SSL certificates for HTTPS
# This script is idempotent - safe to run multiple times

set +e  # Don't exit on error

DOMAIN="rise.is404.net"
CERT_PATH="/etc/letsencrypt/live/${DOMAIN}/fullchain.pem"
KEY_PATH="/etc/letsencrypt/live/${DOMAIN}/privkey.pem"
NGINX_CONF_DIR="/etc/nginx/conf.d"
SSL_CONF="${NGINX_CONF_DIR}/ssl_${DOMAIN}.conf"

echo "=== Nginx SSL Configuration Script ==="
echo "Domain: ${DOMAIN}"

# Check if certificate files exist
if [ ! -f "$CERT_PATH" ] || [ ! -f "$KEY_PATH" ]; then
    echo "⚠️  SSL certificate files not found:"
    echo "   Certificate: ${CERT_PATH}"
    echo "   Key: ${KEY_PATH}"
    echo "Skipping nginx SSL configuration."
    exit 0
fi

echo "✅ Certificate files found."

# Ensure nginx conf.d directory exists
if [ ! -d "$NGINX_CONF_DIR" ]; then
    echo "ERROR: Nginx conf.d directory not found: ${NGINX_CONF_DIR}"
    exit 0
fi

# Create SSL configuration file
# Note: Files in /etc/nginx/conf.d/ are automatically included by EB's default nginx.conf
echo "Creating SSL configuration at ${SSL_CONF}..."

cat > "$SSL_CONF" <<EOF
# SSL Configuration for ${DOMAIN}
# Auto-generated by Elastic Beanstalk postdeploy hook
# This file is included by the default nginx.conf

# HTTP server - redirect all traffic to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};
    
    # Allow Let's Encrypt ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
        try_files \$uri =404;
    }
    
    # Redirect all other HTTP traffic to HTTPS
    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN} www.${DOMAIN};
    
    # SSL certificate configuration
    ssl_certificate ${CERT_PATH};
    ssl_certificate_key ${KEY_PATH};
    
    # Modern SSL configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;
    
    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate ${CERT_PATH};
    
    # Security headers
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    
    # Proxy settings for Node.js app
    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
    
    # Increase body size limit for file uploads
    client_max_body_size 10M;
}
EOF

# Set proper permissions
chmod 644 "$SSL_CONF"

echo "✅ SSL configuration file created."

# Test nginx configuration
echo "Testing nginx configuration..."
if nginx -t 2>&1; then
    echo "✅ Nginx configuration test passed."
    
    # Reload nginx (graceful reload)
    if systemctl is-active --quiet nginx; then
        echo "Reloading nginx..."
        systemctl reload nginx
        echo "✅ Nginx reloaded successfully."
    else
        echo "Starting nginx..."
        systemctl start nginx
        echo "✅ Nginx started successfully."
    fi
else
    echo "⚠️  Nginx configuration test failed. Not reloading nginx."
    echo "Check the configuration file: ${SSL_CONF}"
    exit 0  # Don't fail deployment
fi

echo "✅ Nginx SSL configuration completed successfully."
exit 0

